# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2"
  maven-central:
    type: maven-repository
    url: "https://repo.maven.apache.org/maven2"
  gradle-plugin-portal:
    type: maven-repository
    url: "https://plugins.gradle.org/m2"
  gem-lib:
    type: maven-repository
    url: https://maven.pkg.github.com/Group-Expense-Manager/gem-lib
    username: ${{ secrets.GITHUB_TOKEN }}
    password: ${{ secrets.LIB_TOKEN }}

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries: "*"
    commit-message:
      prefix: "GEM-241 | chore(deps)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
      prefix: "GEM-241-dependabot"
      include: "updates"
    pull-request-title: "GEM-241 | chore(deps): update dependencies"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
