spring:
  data:
    mongodb:
      uri: ${REPORT_CREATOR_DB_URI}


attachment-store:
  url: http://${ATTACHMENT_STORE_SERVICE_SERVICE_HOST}:8080
  read-timeout: 1000ms
  connect-timeout: 1000ms

finance-adapter:
  url: http://${FINANCE_ADAPTER_SERVICE_SERVICE_HOST}:8080
  read-timeout: 1000ms
  connect-timeout: 1000ms

email-sender:
  url: http://${EMAIL_SENDER_SERVICE_SERVICE_HOST}:8080
  read-timeout: 10000ms
  connect-timeout: 1000ms

user-details-manager:
  url: http://${USER_DETAILS_MANAGER_SERVICE_SERVICE_HOST}:8080
  read-timeout: 1000ms
  connect-timeout: 1000ms

group-manager:
  url: http://${GROUP_MANAGER_SERVICE_SERVICE_HOST}:8080
  read-timeout: 1000ms
  connect-timeout: 1000ms
