wiremock:
  server:
    port: 9999

attachment-store:
  url: http://localhost:${wiremock.server.port}
  read-timeout: 10000ms
  connect-timeout: 10000ms

finance-adapter:
  url: http://localhost:${wiremock.server.port}
  read-timeout: 1000ms
  connect-timeout: 1000ms

email-sender:
  url: http://localhost:${wiremock.server.port}
  read-timeout: 1000ms
  connect-timeout: 1000ms

user-details-manager:
  url: http://localhost:${wiremock.server.port}
  read-timeout: 1000ms
  connect-timeout: 1000ms

group-manager:
  url: http://localhost:${wiremock.server.port}
  read-timeout: 1000ms
  connect-timeout: 1000ms

server:
  shutdown: immediate

spring:
  main:
    allow-bean-definition-overriding: true

report-job-executor:
  corePoolSize: 1
  maxPoolSize: 1
  queueCapacity: 3

report-job-producer:
  corePoolSize: 1
  maxPoolSize: 1
  queueCapacity: 1

report-job-processor:
  enabled: true
  lockTime: 10s
  emptyCandidateDelay: 1s
  retryDelays:
    - 0s
