spring:
  application:
    name: report-creator
  data:
    mongodb:
      auto-index-creation: true

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions: []
    attachmentStore:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableAttachmentStoreClientException
      ignoreExceptions: [ ]
    financeAdapter:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableFinanceAdapterClientException
      ignoreExceptions: [ ]
    emailSender:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableEmailSenderClientException
      ignoreExceptions: [ ]
    userDetailsManager:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableUserDetailsManagerClientException
      ignoreExceptions: [ ]
    groupManager:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - pl.edu.agh.gem.internal.client.RetryableGroupManagerClientException
        - java.io.IOException
      ignoreExceptions: [ ]

attachment-store:
  read-timeout: 1000ms
  connect-timeout: 1000ms

finance-adapter:
  read-timeout: 1000ms
  connect-timeout: 1000ms

email-sender:
  read-timeout: 1000ms
  connect-timeout: 1000ms

user-details-manager:
  read-timeout: 1000ms
  connect-timeout: 1000ms

group-manager:
  read-timeout: 1000ms
  connect-timeout: 1000ms

report-job-executor:
  corePoolSize: 2
  maxPoolSize: 2
  queueCapacity: 100

report-job-producer:
  corePoolSize: 1
  maxPoolSize: 1
  queueCapacity: 1

report-job-processor:
  enabled: true
  lockTime: 5m
  emptyCandidateDelay: 3s
  retryDelays:
    - 10s
    - 1m
    - 5m
    - 10m
    - 30m
    - 1h
    - 4h
    - 12h
    - 24h
